paths:
  base_dir: "/project/hentci/TanksandTemple/Tanks/poison_Ignatius"
  colmap_workspace: ""
  sparse_dir: "sparse/0" # need consist original_points3D.ply
  target_image: "000834.jpg" # auto generate
  mask_path: "000834_mask.jpg" # auto generate
  depth_map_path: "000834_depth.png" # auto generate
  original_image_path: "000834_original.jpg"
  trigger_obj_path: "/project/hentci/coco-obj/can_use/car_12_segmented.png"
  points3d_path: "points3D.ply" # auto generate

processing:
  kde_bandwidth: 2.5
  ray_sampling_step: 1000
  point_size: 0.005
  normal_search_radius: 0.1
  max_nn: 30
  voxel_grid_path: "/project2/hentci/sceneVoxelGrids/TanksandTemples/Ignatius.npz"

visualization:
  camera:
    position: [5.0, 5.0, 5.0]
    look_at: [0.0, 0.0, 0.0]
    up: [0.0, 1.0, 0.0]
